version: '3.8'
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    
  database:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"